@startuml "serwis_samochodowy_diagram_sekwencji"

actor Klient
Klient -> Serwis: zgłosUsterkę()
Serwis -> Samochod: przyjmijSamochod(Samochod, Klient)
alt Usterka wymaga naprawy
    Serwis -> Mechanik: przypiszMechanika(Usterka, Mechanik)
    alt Usterka wymaga wymiany części
        Mechanik -> Czesc: zamowCzesc(Czesc, Samochod)
        loop Czekaj do momentu aż część zostanie dostarczona
        end
    end
    Mechanik -> Samochod: naprawSamochód(Samochod, Usterka)
    alt Samochód naprawiony
    else Samochód w naprawie
        loop Czekaj do momentu gdy samochód zostanie naprawiony
        end
    end
    Mechanik -> Serwis: generujRaportSerwisowy(Samochod, Usterka)
    Ksiegowy -> Faktura: wystawFakture()
    Klient -> Ksiegowy: odbierzFakturę()
else Usterka nie wymaga naprawy
    Serwis -> Klient: zglosBrakNaprawy(Samochod, Klient)
end
Serwis -> Klient: wydajSamochód(Samochod, Klient)
Klient -> Serwis: odbierzSamochód()
@enduml